### ISSUE TITLE
A doctor discovers a terrifying secret about herself after she is trapped aboard a colony ship bound for a star.

### ISSUE THREAD

**Issue by hhirsch** [jrmiller82/opensfnovel01#8]
Who would want to colonize a star. It is very hot. @jrmiller82

**Comment by jrmiller82** [comment]
:) Good point. We can refine that to a planet in the 5 sentence break down if we pick that one. Do you like the other one better?

**Comment by hhirsch** [comment]
@jrmiller82 Good. Fine with either one. None is my favorite though see vote. Keep this issue open until we solved it in the breakdown.

**Comment by jrmiller82** [comment]
If it's just you and me, I'm fine with the robot uprising story too. What do you think?

**Comment by hhirsch** [comment]
@jrmiller82 Cool. I'd like that better of course. Can you create an organization and transfer the repo to it? This way we can have both write access and a website for the organization.

**Comment by jrmiller82** [comment]
Does that still remain free? I don't have a paid github account. If still free, I have no problem with that.

**Comment by jrmiller82** [comment]
Done.
